package com.code.db.code_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE CompagniaBase PLEASE EDIT ../Compagnia.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Compagnia object
 * 
 */

import javax.persistence.GeneratedValue;
import javax.persistence.MappedSuperclass;
import javax.persistence.Id;
import javax.persistence.Column;
import java.util.Date;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.FetchType;
import java.util.stream.Collectors;

import com.code.db.code_db.entity.Compagnia;
// Import relations
import com.code.db.code_db.entity.Contatti;




@MappedSuperclass
public class CompagniaBase {
	
	@Id
	@GeneratedValue
	@Column(name = "id")
	private Long _id;
	
	// Attributes
	@Column(nullable=false)
    private String Name;
	
	// Relations Contatti
	@OneToMany(mappedBy="WorkIN")
	private List<Contatti> WorkIN_Contatti = new ArrayList<>();
	
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public String getName() {
		return Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}
    
	// Relations Contatti
	
	public List<Contatti> getContatti() {
		return this.WorkIN_Contatti;
	}

	public void addContatti(Contatti Contatti) {
		this.WorkIN_Contatti.add(Contatti);
	}

	public void removeContatti(Contatti Contatti) {
		this.WorkIN_Contatti.remove(Contatti);
	}
	

    
}