package com.code.db.code_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE ContattiBase PLEASE EDIT ../Contatti.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Contatti object
 * 
 */

import javax.persistence.GeneratedValue;
import javax.persistence.MappedSuperclass;
import javax.persistence.Id;
import javax.persistence.Column;
import java.util.Date;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.FetchType;
import java.util.stream.Collectors;

import com.code.db.code_db.entity.Contatti;
// Import relations
import com.code.db.code_db.entity.Compagnia;




@MappedSuperclass
public class ContattiBase {
	
	@Id
	@GeneratedValue
	@Column(name = "id")
	private Long _id;
	
	// Attributes
	@Column()
    private Date Birthday;
	@Column()
    private String Gender;
	@Column(nullable=false)
    private String Lastname;
	@Column(nullable=false)
    private String Name;
	
	// Relations WorkIN
	@ManyToOne(fetch = FetchType.LAZY)
	private Compagnia WorkIN;
	
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public Date getBirthday() {
		return Birthday;
	}

	public void setBirthday(Date Birthday) {
		this.Birthday = Birthday;
	}
	public String getGender() {
		return Gender;
	}

	public void setGender(String Gender) {
		this.Gender = Gender;
	}
	public String getLastname() {
		return Lastname;
	}

	public void setLastname(String Lastname) {
		this.Lastname = Lastname;
	}
	public String getName() {
		return Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}
    
	public void setCompagnia(String WorkIN) {
		this.WorkIN = new Compagnia(WorkIN);
	}

	public Compagnia getWorkIN() {
		return WorkIN;
	}
	

    
}