package com.code.db.code_db.dtos.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE CompagniaBaseDto PLEASE EDIT ../CompagniaDto.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the dto of Compagnia object
 * 
 */

import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;


import com.code.db.code_db.entity.Compagnia;
// Import relations
import com.code.db.code_db.dtos.infos.ContattiInfo;



public class CompagniaBaseDto {
	
	private Long _id;
	
	// Attributes
    private String Name;
	
	// Relations Contatti
	private List<Long> WorkIN_Contatti = new ArrayList<>();
	
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public String getName() {
		return Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}
    
	// Relations Contatti
	
	public List<Long> getWorkIN_Contatti() {
		return this.WorkIN_Contatti;
	}

    public void setWorkIN_Contatti(List<ContattiInfo> list) {
		this.WorkIN_Contatti = list.stream()
				.map(el -> el.get_id())
				.collect(Collectors.toList());
	}

	

    
}